version: "3.5"

services:
  db:
    image: postgres:11.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: filharmonic
      POSTGRES_PASS: filharmonic
      POSTGRES_DB: filharmonic
