version: "3.5"

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./tests/initDb.sql:/docker-entrypoint-initdb.d/initUser.sql:ro
