[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "v1"
  name = "gopkg.in/gavv/httpexpect.v1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "7.1.6"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.11.0"

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "6.6.3"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/logger"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.14"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.1"

[[constraint]]
  name = "github.com/mailjet/mailjet-apiv3-go"
  version = "2.4.5"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"
