[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "v1"
  name = "gopkg.in/gavv/httpexpect.v1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "7.1.6"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
