// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sessions is an autogenerated mock type for the Sessions type
type Sessions struct {
	mock.Mock
}

// Add provides a mock function with given fields: userId
func (_m *Sessions) Add(userId int64) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Delete provides a mock function with given fields: sessionToken
func (_m *Sessions) Delete(sessionToken string) {
	_m.Called(sessionToken)
}

// Get provides a mock function with given fields: sessionToken
func (_m *Sessions) Get(sessionToken string) int64 {
	ret := _m.Called(sessionToken)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(sessionToken)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Set provides a mock function with given fields: sessionToken, userId
func (_m *Sessions) Set(sessionToken string, userId int64) {
	_m.Called(sessionToken, userId)
}
